"""taxonomy, ai gateway, and analysis domains

Revision ID: 34718a1dd3e4
Revises: a7b9dd2ffb2a
Create Date: 2026-07-20 19:02:09.315273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34718a1dd3e4'
down_revision: Union[str, Sequence[str], None] = 'a7b9dd2ffb2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_evidence_span',
    sa.Column('analysis_label_id', sa.Uuid(), nullable=False),
    sa.Column('feedback_record_id', sa.Uuid(), nullable=False),
    sa.Column('text_variant', sa.Enum('original', 'normalized', 'redacted', name='text_variant'), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('excerpt_snapshot', sa.Text(), nullable=False),
    sa.Column('support_strength', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('end_offset > start_offset', name='ck_analysis_evidence_span_end_after_start'),
    sa.CheckConstraint('start_offset >= 0', name='ck_analysis_evidence_span_start_nonneg'),
    sa.CheckConstraint('support_strength IS NULL OR support_strength BETWEEN 0 AND 1', name='ck_analysis_evidence_span_support_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_label',
    sa.Column('feedback_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('taxonomy_dimension_id', sa.Uuid(), nullable=False),
    sa.Column('taxonomy_label_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('source', sa.Enum('model', 'rule', 'human', 'imported', name='label_source'), nullable=False),
    sa.Column('review_status', sa.Enum('unreviewed', 'accepted', 'edited', 'rejected', 'needs_second_review', name='review_status'), server_default='unreviewed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_analysis_label_confidence_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_run',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_analysis_run_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('created', 'queued', 'running', 'retrying', 'partially_completed', 'completed', 'failed', 'cancelled', name='analysis_run_status'), server_default='created', nullable=False),
    sa.Column('dataset_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('taxonomy_version_id', sa.Uuid(), nullable=False),
    sa.Column('embedding_configuration_id', sa.Uuid(), nullable=True),
    sa.Column('classification_model_configuration_id', sa.Uuid(), nullable=False),
    sa.Column('theme_model_configuration_id', sa.Uuid(), nullable=True),
    sa.Column('insight_model_configuration_id', sa.Uuid(), nullable=True),
    sa.Column('clustering_configuration', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('scoring_profile_id', sa.Uuid(), nullable=True),
    sa.Column('records_selected', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_classified', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_embedded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.Text(), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('records_classified >= 0', name='ck_analysis_run_classified_nonneg'),
    sa.CheckConstraint('records_embedded >= 0', name='ck_analysis_run_embedded_nonneg'),
    sa.CheckConstraint('records_failed >= 0', name='ck_analysis_run_failed_nonneg'),
    sa.CheckConstraint('records_selected >= 0', name='ck_analysis_run_selected_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_analysis',
    sa.Column('feedback_record_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('taxonomy_version_id', sa.Uuid(), nullable=False),
    sa.Column('model_call_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'low_confidence', 'invalid_output', 'failed', 'human_corrected', name='feedback_analysis_status'), server_default='pending', nullable=False),
    sa.Column('overall_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('sentiment_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('severity_value', sa.SmallInteger(), nullable=True),
    sa.Column('severity_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_human_corrected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('supersedes_feedback_analysis_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('overall_confidence IS NULL OR overall_confidence BETWEEN 0 AND 1', name='ck_feedback_analysis_overall_confidence_range'),
    sa.CheckConstraint('sentiment_score IS NULL OR sentiment_score BETWEEN -1 AND 1', name='ck_feedback_analysis_sentiment_range'),
    sa.CheckConstraint('severity_value IS NULL OR severity_value BETWEEN 0 AND 5', name='ck_feedback_analysis_severity_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_call',
    sa.Column('analysis_run_id', sa.Uuid(), nullable=True),
    sa.Column('research_question_id', sa.Uuid(), nullable=True),
    sa.Column('prompt_version_id', sa.Uuid(), nullable=False),
    sa.Column('model_configuration_id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'invalid_output', 'rate_limited', 'timed_out', 'failed', 'cancelled', name='model_call_status'), server_default='queued', nullable=False),
    sa.Column('input_object_type', sa.Text(), nullable=True),
    sa.Column('input_object_ids', sa.ARRAY(sa.Uuid()), nullable=True),
    sa.Column('input_checksum', sa.CHAR(length=64), nullable=False),
    sa.Column('request_payload_redacted', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider_request_id', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_configuration',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('task_type', sa.Text(), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), server_default='30', nullable=False),
    sa.Column('max_retries', sa.Integer(), server_default='3', nullable=False),
    sa.Column('structured_output_mode', sa.Text(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('max_output_tokens IS NULL OR max_output_tokens > 0', name='ck_model_configuration_max_tokens_positive'),
    sa.CheckConstraint('max_retries >= 0', name='ck_model_configuration_retries_nonneg'),
    sa.CheckConstraint('temperature IS NULL OR temperature BETWEEN 0 AND 2', name='ck_model_configuration_temperature_range'),
    sa.CheckConstraint('timeout_seconds > 0', name='ck_model_configuration_timeout_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_template',
    sa.Column('task_key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_schema_key', sa.Text(), nullable=True),
    sa.Column('output_schema_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_key', name='uq_prompt_template_task_key')
    )
    op.create_table('prompt_version',
    sa.Column('prompt_template_id', sa.Uuid(), nullable=False),
    sa.Column('version_key', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt_template', sa.Text(), nullable=False),
    sa.Column('response_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_file_checksum', sa.CHAR(length=64), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'deprecated', name='prompt_status'), server_default='draft', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_template_id', 'version_key', name='uq_prompt_version_template_key')
    )
    op.create_table('taxonomy_dimension',
    sa.Column('taxonomy_version_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cardinality', sa.Enum('single', 'multiple', name='taxonomy_cardinality'), nullable=False),
    sa.Column('value_type', sa.Enum('categorical', 'ordinal', 'numeric', 'boolean', name='taxonomy_value_type'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taxonomy_version_id', 'key', name='uq_taxonomy_dimension_version_key')
    )
    op.create_table('taxonomy_label',
    sa.Column('taxonomy_dimension_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('inclusion_examples', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('exclusion_examples', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('parent_label_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taxonomy_dimension_id', 'key', name='uq_taxonomy_label_dimension_key')
    )
    op.create_table('taxonomy_version',
    sa.Column('version_key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_file_checksum', sa.CHAR(length=64), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'deprecated', name='taxonomy_status'), server_default='draft', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_key', name='uq_taxonomy_version_key')
    )
    # NOTE: autogenerate wanted to drop a dozen indexes here for the same
    # reason as the previous migration — they're hand-written, not declared
    # as SQLAlchemy Index() objects on the ORM models. False positive, removed.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('taxonomy_version')
    op.drop_table('taxonomy_label')
    op.drop_table('taxonomy_dimension')
    op.drop_table('prompt_version')
    op.drop_table('prompt_template')
    op.drop_table('model_configuration')
    op.drop_table('model_call')
    op.drop_table('feedback_analysis')
    op.drop_table('analysis_run')
    op.drop_table('analysis_label')
    op.drop_table('analysis_evidence_span')

    # As in the previous migration: autogenerate's drop_table calls don't
    # drop the enum types Postgres implicitly created for these columns.
    for enum_name in (
        "text_variant",
        "label_source",
        "review_status",
        "feedback_analysis_status",
        "analysis_run_status",
        "model_call_status",
        "prompt_status",
        "taxonomy_status",
        "taxonomy_cardinality",
        "taxonomy_value_type",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
