"""research workspace domain

Revision ID: 73f0a5f58142
Revises: 86cdbc2a53fa
Create Date: 2026-07-21 01:30:57.589788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73f0a5f58142'
down_revision: Union[str, Sequence[str], None] = '86cdbc2a53fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_citation',
    sa.Column('answer_finding_id', sa.Uuid(), nullable=False),
    sa.Column('citation_label', sa.Text(), nullable=False),
    sa.Column('object_type', sa.Enum('feedback_record', 'theme', 'theme_metric', 'insight', name='citation_object_type'), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_role', postgresql.ENUM('supporting', 'contradictory', 'illustrative', 'quantitative_context', name='evidence_role', create_type=False), nullable=False),
    sa.Column('excerpt_snapshot', sa.Text(), nullable=True),
    sa.Column('supports_claim', sa.Boolean(), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_finding_id', 'citation_label', name='uq_answer_citation_finding_label')
    )
    op.create_table('answer_finding',
    sa.Column('generated_answer_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('finding_type', postgresql.ENUM('observed_evidence', 'synthesized_insight', 'product_hypothesis', name='insight_type', create_type=False), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('confidence_level', postgresql.ENUM('low', 'medium', 'high', name='confidence_level', create_type=False), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('support_status', sa.Enum('unverified', 'supported', 'partially_supported', 'unsupported', 'contradicted', name='finding_support_status'), server_default='unverified', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('confidence_score IS NULL OR confidence_score BETWEEN 0 AND 1', name='ck_answer_finding_confidence_range'),
    sa.CheckConstraint('position > 0', name='ck_answer_finding_position_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generated_answer_id', 'position', name='uq_answer_finding_answer_position')
    )
    op.create_table('answer_warning',
    sa.Column('generated_answer_id', sa.Uuid(), nullable=False),
    sa.Column('warning_type', sa.Text(), nullable=False),
    sa.Column('severity', postgresql.ENUM('info', 'warning', 'error', name='quality_event_severity', create_type=False), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_answer',
    sa.Column('research_question_id', sa.Uuid(), nullable=False),
    sa.Column('model_call_id', sa.Uuid(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('answer_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grounding_status', sa.Enum('pending', 'passed', 'passed_with_warnings', 'failed', 'human_reviewed', name='grounding_status'), server_default='pending', nullable=False),
    sa.Column('grounding_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('citation_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('warning_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('observed_evidence_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('synthesized_insight_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('product_hypothesis_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('limitations', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('suggested_validations', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('citation_count >= 0', name='ck_generated_answer_citation_count_nonneg'),
    sa.CheckConstraint('warning_count >= 0', name='ck_generated_answer_warning_count_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_question_id', name='uq_generated_answer_research_question')
    )
    op.create_table('query_plan',
    sa.Column('research_question_id', sa.Uuid(), nullable=False),
    sa.Column('model_call_id', sa.Uuid(), nullable=True),
    sa.Column('research_dimensions', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('query_intent', sa.Enum('explain', 'count', 'compare', 'rank', 'find_examples', 'summarize', 'validate_hypothesis', name='query_intent'), nullable=False),
    sa.Column('structured_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieval_strategy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ambiguity_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requires_deterministic_aggregation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_question_id', name='uq_query_plan_research_question')
    )
    op.create_table('research_question',
    sa.Column('research_session_id', sa.Uuid(), nullable=False),
    sa.Column('parent_question_id', sa.Uuid(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('created', 'planning', 'retrieving', 'generating', 'validating', 'completed', 'completed_with_warnings', 'failed', 'cancelled', name='research_question_status'), server_default='created', nullable=False),
    sa.Column('requested_filters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('effective_filters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('answer_mode', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.Text(), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('char_length(question_text) > 0', name='ck_research_question_text_nonempty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_session',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('theme_set_id', sa.Uuid(), nullable=False),
    sa.Column('insight_set_id', sa.Uuid(), nullable=True),
    sa.Column('default_filters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='research_session_status'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retrieval_result',
    sa.Column('research_question_id', sa.Uuid(), nullable=False),
    sa.Column('object_type', sa.Enum('feedback_record', 'theme', 'insight', name='retrieval_object_type'), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('retrieval_stage', sa.Enum('candidate', 'reranked', 'selected', 'excluded', name='retrieval_stage'), nullable=False),
    sa.Column('vector_score', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('keyword_score', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('structured_filter_score', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('rerank_score', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('diversity_penalty', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('final_rank', sa.Integer(), nullable=True),
    sa.Column('selection_reason', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('final_rank IS NULL OR final_rank > 0', name='ck_retrieval_result_rank_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_question_id', 'object_type', 'object_id', name='uq_retrieval_result_question_object')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retrieval_result')
    op.drop_table('research_session')
    op.drop_table('research_question')
    op.drop_table('query_plan')
    op.drop_table('generated_answer')
    op.drop_table('answer_warning')
    op.drop_table('answer_finding')
    op.drop_table('answer_citation')
    # ### end Alembic commands ###
    op.execute('DROP TYPE IF EXISTS retrieval_stage')
    op.execute('DROP TYPE IF EXISTS retrieval_object_type')
    op.execute('DROP TYPE IF EXISTS research_session_status')
    op.execute('DROP TYPE IF EXISTS research_question_status')
    op.execute('DROP TYPE IF EXISTS query_intent')
    op.execute('DROP TYPE IF EXISTS grounding_status')
    op.execute('DROP TYPE IF EXISTS finding_support_status')
    op.execute('DROP TYPE IF EXISTS citation_object_type')
