"""insight domain

Revision ID: 86cdbc2a53fa
Revises: f7a8ed5b73ce
Create Date: 2026-07-20 23:26:26.768902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86cdbc2a53fa'
down_revision: Union[str, Sequence[str], None] = 'f7a8ed5b73ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insight',
    sa.Column('insight_set_id', sa.Uuid(), nullable=False),
    sa.Column('insight_type', sa.Enum('observed_evidence', 'synthesized_insight', 'product_hypothesis', name='insight_type'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=False),
    sa.Column('affected_context', sa.Text(), nullable=True),
    sa.Column('product_implication', sa.Text(), nullable=True),
    sa.Column('validation_recommendation', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.Enum('low', 'medium', 'high', name='confidence_level'), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('opportunity_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('score_components', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('model_call_id', sa.Uuid(), nullable=True),
    sa.Column('status', postgresql.ENUM('unreviewed', 'accepted', 'edited', 'rejected', 'needs_second_review', name='review_status', create_type=False), server_default='unreviewed', nullable=False),
    sa.Column('supersedes_insight_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('confidence_score IS NULL OR confidence_score BETWEEN 0 AND 1', name='ck_insight_confidence_score_range'),
    sa.CheckConstraint('opportunity_score IS NULL OR opportunity_score >= 0', name='ck_insight_opportunity_score_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insight_evidence',
    sa.Column('insight_id', sa.Uuid(), nullable=False),
    sa.Column('feedback_record_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_role', sa.Enum('supporting', 'contradictory', 'illustrative', 'quantitative_context', name='evidence_role'), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('excerpt_snapshot', sa.Text(), nullable=False),
    sa.Column('review_status', postgresql.ENUM('unreviewed', 'accepted', 'edited', 'rejected', 'needs_second_review', name='review_status', create_type=False), server_default='unreviewed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('(start_offset IS NULL AND end_offset IS NULL) OR (start_offset >= 0 AND end_offset > start_offset)', name='ck_insight_evidence_offsets_valid'),
    sa.CheckConstraint('relevance_score BETWEEN 0 AND 1', name='ck_insight_evidence_relevance_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('insight_id', 'feedback_record_id', 'evidence_role', name='uq_insight_evidence_role')
    )
    op.create_table('insight_set',
    sa.Column('theme_set_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.Enum('draft', 'processing', 'ready_for_review', 'published', 'rejected', 'superseded', name='insight_set_status'), server_default='draft', nullable=False),
    sa.Column('model_configuration_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_version_id', sa.Uuid(), nullable=False),
    sa.Column('insight_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('insight_count >= 0', name='ck_insight_set_count_nonneg'),
    sa.CheckConstraint('version_number > 0', name='ck_insight_set_version_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theme_set_id', 'version_number', name='uq_insight_set_theme_set_version')
    )
    op.create_table('insight_theme',
    sa.Column('insight_id', sa.Uuid(), nullable=False),
    sa.Column('theme_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.Enum('primary', 'supporting', 'contradictory', 'contextual', name='insight_theme_relationship'), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('relevance_score IS NULL OR relevance_score BETWEEN 0 AND 1', name='ck_insight_theme_relevance_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('insight_id', 'theme_id', 'relationship_type', name='uq_insight_theme_relationship')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insight_theme')
    op.drop_table('insight_set')
    op.drop_table('insight_evidence')
    op.drop_table('insight')
    # ### end Alembic commands ###
    op.execute('DROP TYPE IF EXISTS insight_theme_relationship')
    op.execute('DROP TYPE IF EXISTS insight_set_status')
    op.execute('DROP TYPE IF EXISTS insight_type')
    op.execute('DROP TYPE IF EXISTS confidence_level')
    op.execute('DROP TYPE IF EXISTS evidence_role')
