"""source, ingestion, and canonical feedback domains

Migration order steps 2-3 of datamodel.md §80: source/ingestion tables
(datamodel.md Part I) and canonical feedback tables (Part II). Table bodies
were autogenerated from the SQLAlchemy models in sources/, ingestion/, and
feedback/; indexes and the partial unique constraint that aren't expressible
on the ORM models directly were added by hand below.

Revision ID: a7b9dd2ffb2a
Revises: b454289024bc
Create Date: 2026-07-20 12:25:51.174877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7b9dd2ffb2a'
down_revision: Union[str, Sequence[str], None] = 'b454289024bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_checkpoint',
    sa.Column('source_collection_config_id', sa.Uuid(), nullable=False),
    sa.Column('ingestion_run_id', sa.Uuid(), nullable=False),
    sa.Column('checkpoint_type', sa.Text(), nullable=False),
    sa.Column('checkpoint_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_duplicate_link',
    sa.Column('canonical_feedback_record_id', sa.Uuid(), nullable=False),
    sa.Column('duplicate_feedback_record_id', sa.Uuid(), nullable=False),
    sa.Column('duplicate_type', sa.Enum('exact', 'near_duplicate', 'cross_source_repost', 'quoted_copy', name='duplicate_type'), nullable=False),
    sa.Column('lexical_similarity', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('semantic_similarity', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('decision_method', sa.Text(), nullable=False),
    sa.Column('decision_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('canonical_feedback_record_id != duplicate_feedback_record_id', name='ck_feedback_duplicate_link_no_self_reference'),
    sa.CheckConstraint('lexical_similarity IS NULL OR lexical_similarity BETWEEN 0 AND 1', name='ck_feedback_duplicate_link_lexical_range'),
    sa.CheckConstraint('semantic_similarity IS NULL OR semantic_similarity BETWEEN 0 AND 1', name='ck_feedback_duplicate_link_semantic_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('duplicate_feedback_record_id', name='uq_feedback_duplicate_link_duplicate')
    )
    op.create_table('feedback_quality_event',
    sa.Column('feedback_record_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'error', name='quality_event_severity'), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_record',
    sa.Column('raw_source_item_id', sa.Uuid(), nullable=False),
    sa.Column('source_connector_id', sa.Uuid(), nullable=False),
    sa.Column('record_type', sa.Enum('app_review', 'forum_post', 'forum_comment', 'social_post', 'social_comment', 'product_review', 'article_passage', 'other', name='raw_record_type'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('original_title', sa.Text(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('redacted_text', sa.Text(), nullable=False),
    sa.Column('language_code', sa.Text(), nullable=True),
    sa.Column('language_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_code_mixed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('normalized_length', sa.Integer(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=True),
    sa.Column('rating_normalized', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('engagement_count', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.CHAR(length=2), nullable=True),
    sa.Column('app_version', sa.Text(), nullable=True),
    sa.Column('relevance_status', sa.Enum('unreviewed', 'relevant_user_feedback', 'relevant_competitor_feedback', 'industry_commentary', 'irrelevant', 'spam_or_promotion', 'insufficient_content', name='relevance_status'), server_default='unreviewed', nullable=False),
    sa.Column('quality_status', sa.Enum('unassessed', 'usable', 'low_information', 'malformed', 'unsupported_language', 'privacy_blocked', 'collection_incomplete', name='quality_status'), server_default='unassessed', nullable=False),
    sa.Column('processing_status', sa.Enum('collected', 'normalized', 'redacted', 'relevance_assessed', 'deduplicated', 'classified', 'embedded', 'themed', 'insight_linked', 'reviewed', 'failed', name='feedback_processing_status'), server_default='collected', nullable=False),
    sa.Column('is_primary_for_counts', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_deleted_at_source', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('language_confidence IS NULL OR language_confidence BETWEEN 0 AND 1', name='ck_feedback_record_language_confidence_range'),
    sa.CheckConstraint('normalized_length >= 0', name='ck_feedback_record_length_nonneg'),
    sa.CheckConstraint('rating_normalized IS NULL OR rating_normalized BETWEEN 0 AND 1', name='ck_feedback_record_rating_normalized_range'),
    sa.CheckConstraint('token_estimate IS NULL OR token_estimate >= 0', name='ck_feedback_record_token_estimate_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_source_item_id', name='uq_feedback_record_raw_source_item')
    )
    op.create_table('feedback_redaction',
    sa.Column('feedback_record_id', sa.Uuid(), nullable=False),
    sa.Column('redaction_type', sa.Enum('email', 'phone', 'address', 'order_id', 'payment_identifier', 'person_name', 'username', 'other', name='redaction_type'), nullable=False),
    sa.Column('start_offset_original', sa.Integer(), nullable=True),
    sa.Column('end_offset_original', sa.Integer(), nullable=True),
    sa.Column('replacement_token', sa.Text(), nullable=False),
    sa.Column('detector', sa.Text(), nullable=False),
    sa.Column('detector_version', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_thread_relation',
    sa.Column('parent_feedback_record_id', sa.Uuid(), nullable=False),
    sa.Column('child_feedback_record_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.Enum('reply_to', 'comment_on', 'quoted_by', 'context_for', name='thread_relation_type'), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('position_in_thread', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('depth IS NULL OR depth >= 0', name='ck_feedback_thread_relation_depth_nonneg'),
    sa.CheckConstraint('parent_feedback_record_id != child_feedback_record_id', name='ck_feedback_thread_relation_no_self_reference'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_feedback_record_id', 'child_feedback_record_id', 'relation_type', name='uq_feedback_thread_relation')
    )
    op.create_table('ingestion_run',
    sa.Column('source_collection_config_id', sa.Uuid(), nullable=False),
    sa.Column('parent_run_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('created', 'queued', 'running', 'retrying', 'partially_completed', 'completed', 'failed', 'cancelled', name='ingestion_run_status'), server_default='created', nullable=False),
    sa.Column('requested_record_limit', sa.Integer(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('configuration_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checkpoint_start', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checkpoint_end', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('records_discovered', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_stored', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_skipped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('actual_cost_usd', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.Text(), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('date_from IS NULL OR date_to IS NULL OR date_from <= date_to', name='ck_ingestion_run_date_range'),
    sa.CheckConstraint('records_discovered >= 0', name='ck_ingestion_run_discovered_nonneg'),
    sa.CheckConstraint('records_failed >= 0', name='ck_ingestion_run_failed_nonneg'),
    sa.CheckConstraint('records_skipped >= 0', name='ck_ingestion_run_skipped_nonneg'),
    sa.CheckConstraint('records_stored >= 0', name='ck_ingestion_run_stored_nonneg'),
    sa.CheckConstraint('requested_record_limit IS NULL OR requested_record_limit > 0', name='ck_ingestion_run_limit_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_artifact',
    sa.Column('ingestion_run_id', sa.Uuid(), nullable=False),
    sa.Column('storage_backend', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('media_type', sa.Text(), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('request_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('response_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retention_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('byte_size IS NULL OR byte_size >= 0', name='ck_raw_artifact_size_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_backend', 'storage_key', name='uq_raw_artifact_key')
    )
    op.create_table('raw_source_item',
    sa.Column('raw_artifact_id', sa.Uuid(), nullable=False),
    sa.Column('ingestion_run_id', sa.Uuid(), nullable=False),
    sa.Column('source_connector_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('external_parent_id', sa.Text(), nullable=True),
    sa.Column('record_type', sa.Enum('app_review', 'forum_post', 'forum_comment', 'social_post', 'social_comment', 'product_review', 'article_passage', 'other', name='raw_record_type'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author_external_id_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('rating_scale_max', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('engagement_count', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('language_hint', sa.Text(), nullable=True),
    sa.Column('country_code', sa.CHAR(length=2), nullable=True),
    sa.Column('app_version', sa.Text(), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('payload_checksum', sa.CHAR(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('engagement_count IS NULL OR engagement_count >= 0', name='ck_raw_source_item_engagement_nonneg'),
    sa.CheckConstraint('rating IS NULL OR rating >= 0', name='ck_raw_source_item_rating_nonneg'),
    sa.CheckConstraint('rating IS NULL OR rating_scale_max IS NULL OR rating <= rating_scale_max', name='ck_raw_source_item_rating_within_scale'),
    sa.CheckConstraint('rating_scale_max IS NULL OR rating_scale_max > 0', name='ck_raw_source_item_scale_positive'),
    sa.CheckConstraint('reply_count IS NULL OR reply_count >= 0', name='ck_raw_source_item_replies_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_connector_id', 'external_id', name='uq_raw_source_item_connector_external')
    )
    op.create_table('source_collection_config',
    sa.Column('source_connector_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_identifier', sa.Text(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('default_record_limit', sa.Integer(), nullable=True),
    sa.Column('default_date_from', sa.Date(), nullable=True),
    sa.Column('default_date_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by_actor_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('default_date_from IS NULL OR default_date_to IS NULL OR default_date_from <= default_date_to', name='ck_collection_config_date_range'),
    sa.CheckConstraint('default_record_limit IS NULL OR default_record_limit > 0', name='ck_collection_config_limit_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_connector',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('connector_type', sa.Enum('direct_api', 'library', 'playwright', 'apify', 'rss', 'http', name='connector_type'), nullable=False),
    sa.Column('implementation_version', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('supports_incremental', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('supports_thread_context', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('default_rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('default_rate_limit_per_minute IS NULL OR default_rate_limit_per_minute > 0', name='ck_source_connector_rate_limit_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_source_connector_key')
    )
    # NOTE: autogenerate wanted to drop idx_cost_ledger_business_object and
    # idx_job_run_status_created here because they aren't declared as
    # SQLAlchemy Index() objects on the ORM models (they were hand-written
    # in the previous migration). That was a false positive — removed.
    # ### end Alembic commands ###

    # --- Indexes and constraints from datamodel.md not expressible on the
    # ORM models above (partial unique constraint, GIN indexes) ---

    # datamodel.md §7 — partial unique constraint on source_collection_config
    op.create_index(
        "uq_source_collection_config_connector_name",
        "source_collection_config",
        ["source_connector_id", "name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )

    # datamodel.md §8
    op.create_index(
        "idx_ingestion_run_status_created", "ingestion_run", ["status", sa.text("created_at DESC")]
    )
    op.create_index(
        "idx_ingestion_run_config_created",
        "ingestion_run",
        ["source_collection_config_id", sa.text("created_at DESC")],
    )

    # datamodel.md §10
    op.create_index(
        "idx_raw_source_item_published", "raw_source_item", [sa.text("published_at DESC")]
    )
    op.create_index(
        "idx_raw_source_item_connector", "raw_source_item", ["source_connector_id", "record_type"]
    )
    op.create_index(
        "idx_raw_source_item_parent",
        "raw_source_item",
        ["source_connector_id", "external_parent_id"],
        postgresql_where=sa.text("external_parent_id IS NOT NULL"),
    )

    # datamodel.md §11
    op.create_index(
        "idx_connector_checkpoint_latest",
        "connector_checkpoint",
        ["source_collection_config_id", sa.text("created_at DESC")],
    )

    # datamodel.md §12
    op.create_index(
        "idx_feedback_record_filter",
        "feedback_record",
        [
            "relevance_status",
            "quality_status",
            "is_primary_for_counts",
            sa.text("published_at DESC"),
        ],
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "idx_feedback_record_source_date",
        "feedback_record",
        ["source_connector_id", sa.text("published_at DESC")],
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "idx_feedback_record_content_hash", "feedback_record", ["content_hash"]
    )
    op.execute(
        "CREATE INDEX idx_feedback_record_text_trgm ON feedback_record "
        "USING GIN (redacted_text gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX idx_feedback_record_fts ON feedback_record "
        "USING GIN (to_tsvector('simple', coalesce(original_title, '') || ' ' || redacted_text))"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS idx_feedback_record_fts")
    op.execute("DROP INDEX IF EXISTS idx_feedback_record_text_trgm")
    op.drop_index("idx_feedback_record_content_hash", table_name="feedback_record")
    op.drop_index("idx_feedback_record_source_date", table_name="feedback_record")
    op.drop_index("idx_feedback_record_filter", table_name="feedback_record")
    op.drop_index("idx_connector_checkpoint_latest", table_name="connector_checkpoint")
    op.drop_index("idx_raw_source_item_parent", table_name="raw_source_item")
    op.drop_index("idx_raw_source_item_connector", table_name="raw_source_item")
    op.drop_index("idx_raw_source_item_published", table_name="raw_source_item")
    op.drop_index("idx_ingestion_run_config_created", table_name="ingestion_run")
    op.drop_index("idx_ingestion_run_status_created", table_name="ingestion_run")
    op.drop_index(
        "uq_source_collection_config_connector_name", table_name="source_collection_config"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_connector')
    op.drop_table('source_collection_config')
    op.drop_table('raw_source_item')
    op.drop_table('raw_artifact')
    op.drop_table('ingestion_run')
    op.drop_table('feedback_thread_relation')
    op.drop_table('feedback_redaction')
    op.drop_table('feedback_record')
    op.drop_table('feedback_quality_event')
    op.drop_table('feedback_duplicate_link')
    op.drop_table('connector_checkpoint')
    # ### end Alembic commands ###

    # autogenerate's drop_table calls above don't drop the enum types Postgres
    # implicitly created for these columns — without this, a subsequent
    # upgrade() fails with DuplicateObjectError on the first CREATE TABLE that
    # references one of these types.
    for enum_name in (
        "connector_type",
        "ingestion_run_status",
        "raw_record_type",
        "relevance_status",
        "quality_status",
        "feedback_processing_status",
        "thread_relation_type",
        "duplicate_type",
        "redaction_type",
        "quality_event_severity",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
