"""reporting domain

Revision ID: ce417019667f
Revises: d4a1e6f293b7
Create Date: 2026-08-01 19:44:45.641367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce417019667f'
down_revision: Union[str, Sequence[str], None] = 'd4a1e6f293b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('theme_set_id', sa.Uuid(), nullable=False),
    sa.Column('insight_set_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'ready_for_review', 'published', 'archived', name='report_status'), server_default='draft', nullable=False),
    sa.Column('report_configuration', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_evidence_link',
    sa.Column('report_section_id', sa.Uuid(), nullable=False),
    sa.Column('object_type', sa.Enum('feedback_record', 'theme', 'theme_metric', 'insight', 'generated_answer', name='report_evidence_type'), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('display_order > 0', name='ck_report_evidence_link_display_order_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_section_id', 'object_type', 'object_id', name='uq_report_evidence_link_section_object')
    )
    op.create_table('report_export',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('export_format', sa.Enum('markdown', 'json', 'pdf', name='report_export_format'), nullable=False),
    sa.Column('status', sa.Enum('created', 'queued', 'rendering', 'completed', 'failed', 'cancelled', name='report_export_status'), server_default='created', nullable=False),
    sa.Column('storage_backend', sa.Text(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('sha256', sa.CHAR(length=64), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('export_configuration', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('failure_code', sa.Text(), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_section',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('section_type', sa.Enum('executive_summary', 'research_scope', 'coverage', 'key_theme', 'key_insight', 'opportunity', 'contradiction', 'limitation', 'validation_plan', 'methodology', 'appendix', name='report_section_type'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('narrative_text', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('position > 0', name='ck_report_section_position_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'position', name='uq_report_section_report_position')
    )
    # ### end Alembic commands ###
    # NOTE: alembic autogenerate also proposed dropping 15 indexes
    # (idx_embedding_vector_hnsw, idx_feedback_record_fts,
    # idx_feedback_record_text_trgm, etc.) that exist in the live DB but
    # aren't declared as SQLAlchemy Index() objects on their models (they
    # were created via raw SQL in earlier migrations). That's pre-existing
    # ORM/DB drift unrelated to the reporting domain — removed from this
    # migration rather than silently dropping real, performance-critical
    # indexes (HNSW vector search, GIN full-text/trigram search).


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_section')
    op.drop_table('report_export')
    op.drop_table('report_evidence_link')
    op.drop_table('report')
    # ### end Alembic commands ###
