"""embedding and theme domains

Migration order steps 4-5 of datamodel.md §80: embedding configuration/
vectors (Part V) and theme sets/themes/memberships/metrics/scoring
(Part VI). NOTE: autogenerate produced a reference to
`pgvector.sqlalchemy.vector.VECTOR` without importing `pgvector` — that
import was added by hand below; without it this migration would raise
NameError at run time.

Revision ID: f7a8ed5b73ce
Revises: 34718a1dd3e4
Create Date: 2026-07-20 20:17:08.095353

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f7a8ed5b73ce'
down_revision: Union[str, Sequence[str], None] = '34718a1dd3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding',
    sa.Column('embedding_configuration_id', sa.Uuid(), nullable=False),
    sa.Column('object_type', sa.Enum('feedback_record', 'feedback_context_window', 'theme', 'insight', 'research_question', name='embedding_object_type'), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('text_variant', sa.Text(), nullable=False),
    sa.Column('text_checksum', sa.CHAR(length=64), nullable=False),
    sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('token_count IS NULL OR token_count >= 0', name='ck_embedding_token_count_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('embedding_configuration_id', 'object_type', 'object_id', 'text_checksum', name='uq_embedding_config_object_checksum')
    )
    op.create_table('embedding_configuration',
    sa.Column('version_key', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('distance_metric', sa.Text(), server_default='cosine', nullable=False),
    sa.Column('max_input_tokens', sa.Integer(), nullable=True),
    sa.Column('normalization_strategy', sa.Text(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('dimension > 0', name='ck_embedding_configuration_dimension_positive'),
    sa.CheckConstraint('max_input_tokens IS NULL OR max_input_tokens > 0', name='ck_embedding_configuration_max_tokens_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_key', name='uq_embedding_configuration_version_key')
    )
    op.create_table('scoring_profile',
    sa.Column('version_key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalization_rules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('formula_expression', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'deprecated', name='scoring_profile_status'), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_key', name='uq_scoring_profile_version_key')
    )
    op.create_table('theme',
    sa.Column('theme_set_id', sa.Uuid(), nullable=False),
    sa.Column('theme_key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('short_summary', sa.Text(), nullable=False),
    sa.Column('long_summary', sa.Text(), nullable=True),
    sa.Column('theme_type', sa.Enum('repeat_category_driver', 'exploration_barrier', 'discovery_mechanism', 'habit_signal', 'information_need', 'frustration', 'experimentation_signal', 'unmet_need', 'service_quality', 'other', name='theme_type'), nullable=False),
    sa.Column('status', sa.Enum('unreviewed', 'accepted', 'edited', 'rejected', 'merged', 'split', 'superseded', name='theme_status'), server_default='unreviewed', nullable=False),
    sa.Column('model_call_id', sa.Uuid(), nullable=True),
    sa.Column('representative_record_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('coherence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('discovery_relevance_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('actionability_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('opportunity_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('score_components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('coherence_score IS NULL OR coherence_score BETWEEN 0 AND 1', name='ck_theme_coherence_range'),
    sa.CheckConstraint('confidence_score IS NULL OR confidence_score BETWEEN 0 AND 1', name='ck_theme_confidence_range'),
    sa.CheckConstraint('opportunity_score IS NULL OR opportunity_score >= 0', name='ck_theme_opportunity_score_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theme_set_id', 'theme_key', name='uq_theme_set_key')
    )
    op.create_table('theme_membership',
    sa.Column('theme_id', sa.Uuid(), nullable=False),
    sa.Column('feedback_record_id', sa.Uuid(), nullable=False),
    sa.Column('membership_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('assignment_method', sa.Text(), nullable=False),
    sa.Column('is_representative', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_counterexample', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('rank_within_theme', sa.Integer(), nullable=True),
    sa.Column('review_status', postgresql.ENUM('unreviewed', 'accepted', 'edited', 'rejected', 'needs_second_review', name='review_status', create_type=False), server_default='unreviewed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('NOT (is_representative AND is_counterexample)', name='ck_theme_membership_not_both_rep_and_counter'),
    sa.CheckConstraint('membership_score BETWEEN 0 AND 1', name='ck_theme_membership_score_range'),
    sa.CheckConstraint('rank_within_theme IS NULL OR rank_within_theme > 0', name='ck_theme_membership_rank_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theme_id', 'feedback_record_id', name='uq_theme_membership_theme_record')
    )
    op.create_table('theme_metric',
    sa.Column('theme_id', sa.Uuid(), nullable=False),
    sa.Column('metric_key', sa.Text(), nullable=False),
    sa.Column('segment_key', sa.Text(), nullable=True),
    sa.Column('numeric_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('json_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculation_version', sa.Text(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(numeric_value, text_value, json_value) = 1', name='ck_theme_metric_exactly_one_value'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theme_id', 'metric_key', 'segment_key', 'calculation_version', name='uq_theme_metric_key_segment_version')
    )
    op.create_table('theme_set',
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'processing', 'ready_for_review', 'published', 'rejected', 'superseded', name='theme_set_status'), server_default='draft', nullable=False),
    sa.Column('clustering_algorithm', sa.Text(), nullable=False),
    sa.Column('clustering_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('eligible_record_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('clustered_record_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('outlier_record_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('theme_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('coverage_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('stability_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('clustered_record_count >= 0', name='ck_theme_set_clustered_nonneg'),
    sa.CheckConstraint('eligible_record_count >= 0', name='ck_theme_set_eligible_nonneg'),
    sa.CheckConstraint('outlier_record_count >= 0', name='ck_theme_set_outlier_nonneg'),
    sa.CheckConstraint('theme_count >= 0', name='ck_theme_set_theme_count_nonneg'),
    sa.CheckConstraint('version_number > 0', name='ck_theme_set_version_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'version_number', name='uq_theme_set_run_version')
    )
    # NOTE: autogenerate wanted to drop a dozen hand-written indexes here for
    # the same false-positive reason as the previous two migrations. Removed.
    # ### end Alembic commands ###

    # datamodel.md §29 example — HNSW cosine index for similarity search.
    op.execute(
        "CREATE INDEX idx_embedding_vector_hnsw ON embedding "
        "USING hnsw (embedding_vector vector_cosine_ops)"
    )

    # datamodel.md §32
    op.create_index(
        "idx_theme_membership_record", "theme_membership", ["feedback_record_id", "theme_id"]
    )
    op.create_index(
        "idx_theme_membership_rank",
        "theme_membership",
        ["theme_id", sa.text("is_representative DESC"), "rank_within_theme"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("idx_theme_membership_rank", table_name="theme_membership")
    op.drop_index("idx_theme_membership_record", table_name="theme_membership")
    op.execute("DROP INDEX IF EXISTS idx_embedding_vector_hnsw")

    op.drop_table('theme_set')
    op.drop_table('theme_metric')
    op.drop_table('theme_membership')
    op.drop_table('theme')
    op.drop_table('scoring_profile')
    op.drop_table('embedding_configuration')
    op.drop_table('embedding')

    # As in the previous two migrations: autogenerate's drop_table calls
    # don't drop the enum types Postgres implicitly created for these columns.
    for enum_name in (
        "embedding_object_type",
        "theme_set_status",
        "theme_type",
        "theme_status",
        "scoring_profile_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
