"""validation domain

Revision ID: f918156187f0
Revises: 73f0a5f58142
Create Date: 2026-07-21 02:30:31.528677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f918156187f0'
down_revision: Union[str, Sequence[str], None] = '73f0a5f58142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation',
    sa.Column('evaluation_dataset_item_id', sa.Uuid(), nullable=False),
    sa.Column('annotator_actor_id', sa.Uuid(), nullable=True),
    sa.Column('annotation_round', sa.Integer(), server_default='1', nullable=False),
    sa.Column('annotation_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_adjudicated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('annotation_round > 0', name='ck_annotation_round_positive'),
    sa.CheckConstraint('confidence IS NULL OR confidence BETWEEN 0 AND 1', name='ck_annotation_confidence_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_dataset',
    sa.Column('version_key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('evaluation_type', sa.Enum('classification', 'retrieval', 'theme', 'grounding', name='evaluation_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('taxonomy_version_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_review', 'locked', 'deprecated', name='evaluation_dataset_status'), server_default='draft', nullable=False),
    sa.Column('item_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('selection_method', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('item_count >= 0', name='ck_evaluation_dataset_item_count_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_key', name='uq_evaluation_dataset_version_key')
    )
    op.create_table('evaluation_dataset_item',
    sa.Column('evaluation_dataset_id', sa.Uuid(), nullable=False),
    sa.Column('object_type', sa.Enum('feedback_record', 'research_question', 'theme', 'generated_answer', name='evaluation_object_type'), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gold_output', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_dataset_id', 'object_type', 'object_id', name='uq_evaluation_dataset_item_object')
    )
    op.create_table('evaluation_metric',
    sa.Column('evaluation_run_id', sa.Uuid(), nullable=False),
    sa.Column('metric_key', sa.Text(), nullable=False),
    sa.Column('dimension_key', sa.Text(), nullable=True),
    sa.Column('numeric_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('json_value', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('calculation_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(numeric_value, json_value) = 1', name='ck_evaluation_metric_exactly_one_value'),
    sa.CheckConstraint('sample_count >= 0', name='ck_evaluation_metric_sample_count_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_run_id', 'metric_key', 'dimension_key', name='uq_evaluation_metric_run_key_dimension')
    )
    op.create_table('evaluation_run',
    sa.Column('evaluation_dataset_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=True),
    sa.Column('model_configuration_id', sa.Uuid(), nullable=True),
    sa.Column('prompt_version_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('created', 'running', 'completed', 'completed_with_warnings', 'failed', 'cancelled', name='evaluation_run_status'), server_default='created', nullable=False),
    sa.Column('configuration_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('items_evaluated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('items_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('items_evaluated >= 0', name='ck_evaluation_run_items_evaluated_nonneg'),
    sa.CheckConstraint('items_failed >= 0', name='ck_evaluation_run_items_failed_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_decision',
    sa.Column('object_type', sa.Enum('feedback_relevance', 'feedback_analysis', 'analysis_label', 'theme', 'theme_membership', 'insight', 'insight_evidence', 'answer_finding', 'answer_citation', name='review_object_type'), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_actor_id', sa.Uuid(), nullable=True),
    sa.Column('decision', postgresql.ENUM('unreviewed', 'accepted', 'edited', 'rejected', 'needs_second_review', name='review_status', create_type=False), nullable=False),
    sa.Column('previous_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('edited_snapshot', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('reason_code', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_decision')
    op.drop_table('evaluation_run')
    op.drop_table('evaluation_metric')
    op.drop_table('evaluation_dataset_item')
    op.drop_table('evaluation_dataset')
    op.drop_table('annotation')
    # ### end Alembic commands ###
    op.execute('DROP TYPE IF EXISTS review_object_type')
    op.execute('DROP TYPE IF EXISTS evaluation_run_status')
    op.execute('DROP TYPE IF EXISTS evaluation_object_type')
    op.execute('DROP TYPE IF EXISTS evaluation_dataset_status')
    op.execute('DROP TYPE IF EXISTS evaluation_type')
